--Find total customers by countries

SELECT country ,COUNT(customer_key) AS total_customer
FROM gold.dim_customer
GROUP BY country
ORDER BY total_customer DESC;
GO

--Find total customers by gender

SELECT gender ,COUNT(customer_key) AS total_customer
FROM gold.dim_customer 
GROUP BY  gender
ORDER BY total_customer desc;
GO

--Find total products by category

SELECT p.category,COUNT(p.product_key) AS total_product
FROM gold.dim_products p
GROUP BY p.category
ORDER BY total_product DESC;
GO

--What is the average costs in each category?

SELECT category,AVG(cost) AS avg_costs
FROM gold.dim_products 
GROUP BY category
ORDER BY avg_costs DESC;
GO


--What is the total revenue generated for each category?

SELECT 
p.category
,SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
GO

--Find total revenue is generated by each customer

SELECT c.customer_key
,c.first_name,c.last_name 
,SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN  gold.dim_customer c ON c.customer_key=f.customer_key
GROUP BY c.customer_key
,c.first_name,c.last_name 
ORDER BY total_revenue DESC;
GO

--What is the distribution of sold items across countries?

SELECT 
c.country
,COUNT(f.quantity) AS total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer c ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;
GO

